"""Unity Catalog table and column comment definitions for the bronze layer.

Bronze tables are created by Lakeflow Connect. Comments are applied after ingestion
via the silver DLT pipeline (see src/silver/apply_comments.py).
"""

BRONZE_TABLE_COMMENTS: dict[str, dict[str, object]] = {
    "issues_without_deletes": {
        "comment": "Raw Jira issues from Lakeflow Connect (active issues; deletes excluded by connector).",
        "columns": {
            "id": "Jira issue id.",
            "key": "Human-readable issue key (e.g. PROJ-123).",
            "projectKey": "Project key the issue belongs to.",
            "summary": "Issue summary / title.",
            "description": "Issue description body.",
            "status": "Current workflow status name.",
            "priority": "Priority name.",
            "priorityId": "Priority id.",
            "issueType": "Issue type name (Story, Bug, Epic, …).",
            "resolution": "Resolution name when resolved.",
            "reporter": "Reporter account id.",
            "assignee": "Assignee account id.",
            "creator": "Creator account id.",
            "parent_id": "Parent issue id for sub-tasks and epic children.",
            "created": "Issue creation timestamp.",
            "updated": "Last update timestamp.",
            "resolutionDate": "Resolution timestamp.",
            "due_date": "Due date.",
            "environment": "Environment field.",
            "labels": "Issue labels array.",
            "sprint_ids": "Sprint ids the issue belongs to.",
            "sprints": "Sprint membership (alternate column name).",
            "story_points": "Story points estimate.",
            "original_estimate_seconds": "Original time estimate in seconds.",
            "remaining_estimate_seconds": "Remaining estimate in seconds.",
            "time_spent_seconds": "Time spent in seconds.",
            "watch_count": "Number of watchers.",
            "vote_count": "Number of votes.",
            "components": "Component ids or names on the issue.",
            "component_ids": "Component ids on the issue.",
            "fix_versions": "Fix version ids or names.",
            "fix_version_ids": "Fix version ids on the issue.",
        },
    },
    "issue_comments": {
        "comment": "Raw issue comments from Lakeflow Connect.",
        "columns": {
            "id": "Comment id.",
            "issue_id": "Parent issue id.",
            "issueId": "Parent issue id (camelCase).",
            "author_account_id": "Comment author account id.",
            "author": "Comment author account id (alternate).",
            "update_author_account_id": "Author of the last comment edit.",
            "update_author": "Last editor account id (alternate).",
            "body": "Comment body.",
            "created": "Comment creation timestamp.",
            "updated": "Comment last-updated timestamp.",
        },
    },
    "issue_field_values": {
        "comment": "Raw issue field values (current and historical) from Lakeflow Connect.",
        "columns": {
            "issue_id": "Issue id.",
            "field_id": "Jira field id.",
            "field_value": "Scalar field value.",
            "value": "Field value (alternate column name).",
            "updated_at": "Timestamp when this value became current.",
            "is_current": "Whether this row is the current value for the field.",
            "ingestion_timestamp": "Lakeflow ingestion timestamp.",
        },
    },
    "issue_fields": {
        "comment": "Jira field metadata from Lakeflow Connect.",
        "columns": {
            "id": "Field id.",
            "name": "Field display name.",
            "description": "Field description.",
            "custom": "Whether the field is custom.",
            "is_custom": "Custom flag (alternate column name).",
            "schema_type": "Field schema type (string, array, …).",
            "type": "Field type (alternate column name).",
            "schema_items": "Array item type when schema_type is array.",
        },
    },
    "issue_links": {
        "comment": "Directed links between issues from Lakeflow Connect.",
        "columns": {
            "source_issue_id": "Source issue id.",
            "issue_id": "Source issue id (alternate).",
            "target_issue_id": "Target / related issue id.",
            "related_issue_id": "Related issue id (alternate).",
            "link_type_id": "Link type id.",
            "link_type_name": "Link type name.",
            "relationship": "Link relationship label.",
            "inward": "Inward link description.",
            "outward": "Outward link description.",
        },
    },
    "issue_types": {
        "comment": "Issue type lookup from Lakeflow Connect.",
        "columns": {
            "id": "Issue type id.",
            "name": "Issue type name.",
            "description": "Issue type description.",
            "icon_url": "Icon URL.",
            "subtask": "Whether this type represents sub-tasks.",
            "is_subtask": "Sub-task flag (alternate column name).",
        },
    },
    "issue_watchers": {
        "comment": "Issue watchers from Lakeflow Connect.",
        "columns": {
            "issue_id": "Issue id.",
            "issueId": "Issue id (camelCase).",
            "watcher_account_id": "Watcher account id.",
            "userId": "Watcher user id (alternate).",
            "watcher_id": "Watcher id (alternate).",
        },
    },
    "issue_worklogs": {
        "comment": "Issue worklogs from Lakeflow Connect.",
        "columns": {
            "id": "Worklog id.",
            "issue_id": "Issue id.",
            "issueId": "Issue id (camelCase).",
            "author_account_id": "Worklog author account id.",
            "author_id": "Author id (alternate).",
            "author": "Author account id (alternate).",
            "time_spent_seconds": "Time logged in seconds.",
            "started": "Worklog start timestamp.",
            "started_at": "Worklog start timestamp (alternate).",
            "created": "Worklog creation timestamp.",
            "updated": "Worklog update timestamp.",
            "comment": "Worklog comment text.",
        },
    },
    "projects": {
        "comment": "Jira projects from Lakeflow Connect.",
        "columns": {
            "id": "Project id.",
            "key": "Project key.",
            "project_key": "Project key (alternate).",
            "name": "Project name.",
            "description": "Project description.",
            "project_category_id": "Project category id.",
            "projectCategory": "Project category reference.",
            "project_type_key": "Project type key.",
            "projectTypeKey": "Project type key (camelCase).",
            "lead_account_id": "Project lead account id.",
            "lead": "Project lead account id (alternate).",
            "url": "Project URL.",
            "style": "Project style (classic, next-gen).",
            "archived": "Whether the project is archived.",
            "is_archived": "Archived flag (alternate).",
        },
    },
    "project_board": {
        "comment": "Project-to-board mapping from Lakeflow Connect.",
        "columns": {
            "project_id": "Project id.",
            "projectId": "Project id (camelCase).",
            "board_id": "Board id.",
            "boardId": "Board id (camelCase).",
        },
    },
    "project_categories": {
        "comment": "Project categories from Lakeflow Connect.",
        "columns": {
            "id": "Category id.",
            "name": "Category name.",
            "description": "Category description.",
        },
    },
    "project_components": {
        "comment": "Project components from Lakeflow Connect.",
        "columns": {
            "id": "Component id.",
            "name": "Component name.",
            "description": "Component description.",
            "lead_account_id": "Component lead account id.",
            "lead": "Component lead (alternate).",
            "project_id": "Owning project id.",
            "projectId": "Owning project id (camelCase).",
            "assignee_type": "Default assignee type for the component.",
            "assigneeType": "Assignee type (camelCase).",
        },
    },
    "project_permissions": {
        "comment": "Project permission grants from Lakeflow Connect.",
        "columns": {
            "project_id": "Project id.",
            "permission": "Permission key.",
            "holder_type": "Grant holder type (user, group, …).",
            "holder_value": "Grant holder identifier.",
        },
    },
    "project_role_actor": {
        "comment": "Project role actor assignments from Lakeflow Connect.",
        "columns": {
            "project_id": "Project id.",
            "projectId": "Project id (camelCase).",
            "role_id": "Role id.",
            "roleId": "Role id (camelCase).",
            "actor_id": "Actor id (user or group).",
            "actorId": "Actor id (camelCase).",
            "actor_type": "Actor type.",
            "actorType": "Actor type (camelCase).",
            "actor_name": "Actor display name.",
            "actorName": "Actor name (camelCase).",
        },
    },
    "project_roles": {
        "comment": "Project roles from Lakeflow Connect.",
        "columns": {
            "id": "Role id.",
            "name": "Role name.",
            "description": "Role description.",
        },
    },
    "boards": {
        "comment": "Agile boards from Lakeflow Connect.",
        "columns": {
            "id": "Board id.",
            "name": "Board name.",
            "type": "Board type (scrum, kanban).",
            "board_type": "Board type (alternate).",
            "project_id": "Primary project id.",
            "projectId": "Project id (camelCase).",
            "filter_id": "Saved filter id backing the board.",
            "filterId": "Filter id (camelCase).",
            "location_type": "Board location type.",
            "location": "Board location (alternate).",
        },
    },
    "sprints": {
        "comment": "Agile sprints from Lakeflow Connect.",
        "columns": {
            "id": "Sprint id.",
            "board_id": "Board id.",
            "boardId": "Board id (camelCase).",
            "name": "Sprint name.",
            "state": "Sprint state (future, active, closed).",
            "start_date": "Sprint start timestamp.",
            "startDate": "Sprint start (camelCase).",
            "end_date": "Sprint end timestamp.",
            "endDate": "Sprint end (camelCase).",
            "complete_date": "Sprint completion timestamp.",
            "completeDate": "Completion timestamp (camelCase).",
            "goal": "Sprint goal.",
        },
    },
    "application_roles": {
        "comment": "Jira application roles from Lakeflow Connect.",
        "columns": {
            "key": "Application role key.",
            "name": "Role name.",
            "description": "Role description.",
            "user_count": "Number of users in the role.",
            "group_count": "Number of groups in the role.",
        },
    },
    "priority": {
        "comment": "Issue priority lookup from Lakeflow Connect.",
        "columns": {
            "id": "Priority id.",
            "name": "Priority name.",
            "description": "Priority description.",
            "status_color": "Display color.",
            "color": "Display color (alternate).",
            "icon_url": "Icon URL.",
        },
    },
    "resolutions": {
        "comment": "Issue resolution lookup from Lakeflow Connect.",
        "columns": {
            "id": "Resolution id.",
            "name": "Resolution name.",
            "description": "Resolution description.",
        },
    },
    "status": {
        "comment": "Workflow status lookup from Lakeflow Connect.",
        "columns": {
            "id": "Status id.",
            "name": "Status name.",
            "description": "Status description.",
            "status_category_id": "Status category id or name.",
            "status_category": "Status category reference.",
            "icon_url": "Icon URL.",
        },
    },
    "status_category": {
        "comment": "Status category lookup (To Do / In Progress / Done) from Lakeflow Connect.",
        "columns": {
            "id": "Status category id.",
            "name": "Category name.",
            "key": "Category key (new, indeterminate, done).",
            "category_key": "Category key (alternate).",
            "color_name": "Display color name.",
        },
    },
    "security_level": {
        "comment": "Issue security levels from Lakeflow Connect.",
        "columns": {
            "id": "Security level id.",
            "name": "Security level name.",
            "description": "Security level description.",
            "security_scheme_id": "Parent security scheme id.",
        },
    },
    "security_schemes": {
        "comment": "Issue security schemes from Lakeflow Connect.",
        "columns": {
            "id": "Security scheme id.",
            "name": "Scheme name.",
            "description": "Scheme description.",
            "default_security_level_id": "Default security level id.",
        },
    },
    "permission_schemes": {
        "comment": "Permission schemes from Lakeflow Connect.",
        "columns": {
            "id": "Permission scheme id.",
            "name": "Scheme name.",
            "description": "Scheme description.",
        },
    },
    "users": {
        "comment": "Jira users from Lakeflow Connect.",
        "columns": {
            "account_id": "Atlassian account id.",
            "id": "Account id (alternate).",
            "display_name": "Display name.",
            "displayName": "Display name (camelCase).",
            "email_address": "Email address.",
            "email": "Email (alternate).",
            "emailId": "Email id (alternate).",
            "active": "Whether the user is active.",
            "is_active": "Active flag (alternate).",
            "account_type": "Account type.",
            "accountType": "Account type (camelCase).",
            "locale": "User locale.",
            "time_zone": "User time zone.",
            "timeZone": "Time zone (camelCase).",
        },
    },
    "user_group": {
        "comment": "User-to-group membership from Lakeflow Connect.",
        "columns": {
            "account_id": "User account id.",
            "group_id": "Group id.",
            "group_name": "Group name.",
        },
    },
    "version": {
        "comment": "Project versions / releases from Lakeflow Connect.",
        "columns": {
            "id": "Version id.",
            "name": "Version name.",
            "description": "Version description.",
            "project_id": "Owning project id.",
            "archived": "Whether the version is archived.",
            "released": "Whether the version is released.",
            "release_date": "Release date.",
            "start_date": "Start date.",
        },
    },
}
