"""Unity Catalog table and column comment definitions for the gold layer."""

GOLD_TABLE_COMMENTS: dict[str, dict[str, object]] = {
    "dim_user": {
        "comment": "Conformed user dimension with group memberships flattened to a comma list.",
        "columns": {
            "account_id": "Atlassian account id.",
            "display_name": "User display name.",
            "email": "Email address.",
            "is_active": "Whether the user is active.",
            "account_type": "Account type.",
            "locale": "User locale.",
            "time_zone": "User time zone.",
            "groups": "Comma-separated group names.",
        },
    },
    "dim_project": {
        "comment": "Project dimension with category, lead name, and current issue counts.",
        "columns": {
            "project_id": "Project id.",
            "project_key": "Project key.",
            "project_name": "Project name.",
            "description": "Project description.",
            "project_type_key": "Project type key.",
            "category_name": "Project category name.",
            "lead_id": "Project lead account id.",
            "lead_name": "Project lead display name.",
            "is_archived": "Whether the project is archived.",
            "total_issues": "Total issues in the project.",
            "open_issues": "Open issues in the project.",
            "resolved_issues": "Resolved issues in the project.",
        },
    },
    "dim_status": {
        "comment": "Status with its category (To Do / In Progress / Done) and a derived sort order.",
        "columns": {
            "status_id": "Status id.",
            "status_name": "Status name.",
            "category_key": "Status category key (new, indeterminate, done).",
            "category_name": "Status category display name.",
            "color_name": "Display color name.",
            "category_order": "Sort order for status categories.",
        },
    },
    "dim_sprint": {
        "comment": "Sprint dimension with board, project (inferred), and effective duration.",
        "columns": {
            "sprint_id": "Sprint id.",
            "sprint_name": "Sprint name.",
            "state": "Sprint state (future, active, closed).",
            "start_date": "Sprint start timestamp.",
            "end_date": "Sprint end timestamp.",
            "complete_date": "Sprint completion timestamp.",
            "goal": "Sprint goal.",
            "board_id": "Board id.",
            "board_name": "Board name.",
            "project_id": "Inferred project id from board.",
            "duration_days": "Sprint duration in days.",
        },
    },
    "dim_date": {
        "comment": "Date dimension covering 2 years before earliest issue creation through 1 year ahead.",
        "columns": {
            "date_key": "Calendar date.",
            "year": "Year.",
            "quarter": "Quarter of year.",
            "month": "Month of year.",
            "month_name": "Month name.",
            "iso_week": "ISO week of year.",
            "day_of_month": "Day of month.",
            "day_of_week": "Day of week.",
            "day_name": "Day name.",
            "is_weekend": "Whether the date falls on a weekend.",
        },
    },
    "fct_issue": {
        "comment": "Denormalized issue fact with cycle time, lead time, and current sprint.",
        "columns": {
            "issue_id": "Jira issue id.",
            "issue_key": "Human-readable issue key.",
            "summary": "Issue summary.",
            "project_id": "Project id.",
            "project_key": "Project key.",
            "project_name": "Project name.",
            "issue_type": "Issue type name.",
            "status_name": "Current status name.",
            "status_category": "Status category (To Do / In Progress / Done).",
            "priority": "Priority name.",
            "resolution": "Resolution name.",
            "assignee_name": "Assignee display name.",
            "reporter_name": "Reporter display name.",
            "current_sprint_name": "Current sprint name.",
            "created_at": "Issue creation timestamp.",
            "resolved_at": "Resolution timestamp.",
            "story_points": "Story points estimate.",
            "is_resolved": "Whether the issue is resolved.",
            "cycle_time_days": "Days from first in-progress to resolved.",
            "lead_time_days": "Days from created to resolved.",
            "age_days": "Days since creation for open issues.",
            "age_bucket": "Age bucket for open issues.",
        },
    },
    "fct_sprint_velocity": {
        "comment": "One row per sprint with story points planned/completed and scope change deltas.",
        "columns": {
            "sprint_id": "Sprint id.",
            "sprint_name": "Sprint name.",
            "state": "Sprint state.",
            "project_key": "Project key.",
            "issues_in_sprint": "Issues in the sprint.",
            "issues_completed": "Issues completed in the sprint.",
            "points_in_sprint": "Story points planned.",
            "points_completed": "Story points completed.",
            "completion_ratio": "Ratio of points completed to planned.",
        },
    },
    "fct_issue_transitions": {
        "comment": "Status transition fact derived from issue_field_history (field_id = status).",
        "columns": {
            "issue_id": "Issue id.",
            "project_id": "Project id.",
            "issue_key": "Issue key.",
            "from_status": "Previous status name.",
            "to_status": "New status name.",
            "to_category_key": "Status category key after transition.",
            "entered_at": "Timestamp when the issue entered the to-status.",
            "exited_at": "Timestamp when the issue left the to-status.",
            "duration_hours": "Hours spent in the previous status.",
        },
    },
    "fct_worklog": {
        "comment": "Worklog fact denormalized with project and assignee.",
        "columns": {
            "worklog_id": "Worklog id.",
            "issue_id": "Issue id.",
            "issue_key": "Issue key.",
            "project_key": "Project key.",
            "project_name": "Project name.",
            "author_name": "Worklog author display name.",
            "time_spent_hours": "Time logged in hours.",
            "work_date": "Date work was logged.",
        },
    },
    "agg_project_health": {
        "comment": "Per-project KPIs used on the portfolio page.",
        "columns": {
            "project_id": "Project id.",
            "project_key": "Project key.",
            "project_name": "Project name.",
            "total_issues": "Total issues.",
            "open_issues": "Open issues.",
            "resolved_issues": "Resolved issues.",
            "open_critical": "Open critical-priority issues.",
            "stale_open": "Open issues older than 30 days.",
            "avg_cycle_time_days": "Average cycle time in days.",
            "resolved_last_30d": "Issues resolved in the last 30 days.",
        },
    },
    "agg_assignee_load": {
        "comment": "Current load per assignee: open issues split by priority and age bucket.",
        "columns": {
            "assignee_id": "Assignee account id.",
            "assignee_name": "Assignee display name.",
            "project_id": "Project id.",
            "project_key": "Project key.",
            "priority": "Issue priority.",
            "age_bucket": "Age bucket for open issues.",
            "open_issues": "Count of open issues.",
            "open_story_points": "Sum of open story points.",
            "avg_age_days": "Average age of open issues in days.",
        },
    },
    "agg_team_productivity": {
        "comment": "Per-assignee productivity over the last 90 days.",
        "columns": {
            "assignee_id": "Assignee account id.",
            "assignee_name": "Assignee display name.",
            "resolved_30d": "Issues resolved in the last 30 days.",
            "resolved_90d": "Issues resolved in the last 90 days.",
            "open_now": "Currently open issues.",
            "open_critical": "Currently open critical issues.",
            "avg_cycle_time_days": "Average cycle time in days.",
        },
    },
    "agg_time_in_status": {
        "comment": "Time-in-status distribution per (project, status), used for p50/p90.",
        "columns": {
            "project_id": "Project id.",
            "project_key": "Project key.",
            "status_name": "Workflow status name.",
            "status_category_key": "Status category key.",
            "observations": "Number of transition observations.",
            "p50_hours": "Median hours in status.",
            "p90_hours": "90th percentile hours in status.",
            "avg_hours": "Average hours in status.",
        },
    },
}
