"""Per-field and per-measure COMMENT text for Unity Catalog metric views."""

METRIC_VIEW_COLUMN_COMMENTS: dict[str, dict[str, dict[str, str]]] = {
    "metric_issue": {
        "fields": {
            "Issue Key": "Human-readable issue key (e.g. PROJ-123).",
            "Summary": "Issue summary / title.",
            "Project Key": "Project key for filtering and grouping.",
            "Project Name": "Project display name.",
            "Project Lead": "Project lead display name.",
            "Project Category": "Project category name.",
            "Issue Type": "Issue type (Story, Bug, Epic, …).",
            "Status": "Current workflow status.",
            "Status Category": "To Do, In Progress, or Done.",
            "Priority": "Issue priority.",
            "Assignee": "Current assignee display name.",
            "Current Sprint": "Active sprint name when applicable.",
            "Age Bucket": "Open-issue age bucket.",
            "Is Resolved": "Whether the issue is resolved.",
            "Created Date": "Issue creation date.",
            "Resolved Date": "Issue resolution date.",
            "Created Week": "Week the issue was created (for inflow trends).",
            "Resolved Week": "Week the issue was resolved (for outflow trends).",
            "Due Date": "Issue due date when set.",
            "Reporter": "Issue reporter display name.",
            "Priority Group": "Critical / High / Medium / Low band for cleaner charts.",
            "Is Unassigned": "True when the issue has no assignee.",
            "Is Overdue": "True when an open issue is past its due date.",
            "Is WIP": "True when the issue is open and In Progress.",
        },
        "measures": {
            "Issue Count": "Total number of issues.",
            "Open Issues": "Count of unresolved issues.",
            "Resolved Issues": "Count of resolved issues.",
            "Open Critical": "Open issues with critical/highest priority.",
            "Stale Open": "Open issues older than 30 days.",
            "WIP Issues": "Open issues currently In Progress.",
            "To Do Issues": "Open issues in To Do.",
            "Unassigned Open": "Open issues with no assignee.",
            "Overdue Open": "Open issues past their due date.",
            "Created (7d)": "Issues created in the last 7 days.",
            "Created (30d)": "Issues created in the last 30 days (inflow).",
            "Created (90d)": "Issues created in the last 90 days.",
            "Resolved (7d)": "Issues resolved in the last 7 days.",
            "Resolved (30d)": "Issues resolved in the last 30 days (outflow / throughput).",
            "Resolved (90d)": "Issues resolved in the last 90 days.",
            "Median Cycle Time (days)": "Median days from in-progress to resolved.",
            "P90 Cycle Time (days)": "90th percentile cycle time in days.",
            "Total Story Points": "Sum of story points.",
            "Open Story Points": "Story points on unresolved issues.",
            "Resolved Story Points": "Story points on resolved issues (delivered points).",
        },
    },
    "metric_sprint_velocity": {
        "fields": {
            "Sprint": "Sprint name.",
            "Sprint State": "Sprint state (future, active, closed).",
            "Project Key": "Project key.",
            "Start Date": "Sprint start date.",
            "Complete Date": "Sprint completion date.",
        },
        "measures": {
            "Points Planned": "Story points committed to the sprint.",
            "Points Completed": "Story points completed in the sprint.",
            "Avg Completion Ratio": "Average ratio of completed to planned points.",
            "Issues Planned": "Issues in the sprint.",
            "Issues Completed": "Issues completed in the sprint.",
            "Carryover Points": "Planned points minus completed points.",
            "Carryover Issues": "Planned issues minus completed issues.",
        },
    },
    "metric_issue_transitions": {
        "fields": {
            "Project Key": "Project key.",
            "From Status": "Previous workflow status.",
            "To Status": "New workflow status.",
        },
        "measures": {
            "Transition Count": "Number of status transitions.",
            "P90 Duration (hours)": "90th percentile hours in the previous status.",
            "Median Duration (hours)": "Median hours in the previous status.",
        },
    },
    "metric_worklog": {
        "fields": {
            "Project Key": "Project key.",
            "Author": "Worklog author display name.",
            "Work Date": "Date work was logged.",
        },
        "measures": {
            "Total Hours": "Total logged hours.",
            "Hours (7d)": "Hours logged in the last 7 days.",
            "Hours (30d)": "Hours logged in the last 30 days.",
            "Avg Hours per Entry": "Average logged hours per worklog entry.",
            "Contributors": "Distinct contributors.",
        },
    },
    "metric_project_health": {
        "fields": {
            "Project Key": "Project key.",
            "Project Name": "Project display name.",
            "Project Lead": "Project lead display name.",
        },
        "measures": {
            "Open Issues": "Open issues in the project.",
            "Open Critical": "Open critical-priority issues.",
            "Stale Open": "Open issues older than 30 days.",
            "Resolved Issues (30d)": "Issues resolved in the last 30 days.",
            "Created Issues (30d)": "Issues created in the last 30 days.",
            "Net Backlog Change (30d)": "Created minus resolved in the last 30 days. Positive means the backlog grew.",
            "Flow Ratio (30d)": "Resolved / created in the last 30 days. Above 1 means the team is catching up.",
        },
    },
    "metric_assignee_load": {
        "fields": {
            "Assignee": "Assignee display name.",
            "Project Key": "Project key.",
            "Priority": "Issue priority.",
            "Age Bucket": "Age bucket for open issues.",
        },
        "measures": {
            "Open Issues": "Open issues for the assignee.",
            "Open Story Points": "Sum of open story points.",
            "Stale Open": "Open issues in the 30-90d or 90d+ age buckets.",
        },
    },
    "metric_team_productivity": {
        "fields": {
            "Assignee": "Team member display name.",
        },
        "measures": {
            "Resolved (30d)": "Issues resolved in the last 30 days.",
            "Resolved (90d)": "Issues resolved in the last 90 days.",
            "Open Now": "Currently open issues.",
            "Avg Cycle Time (days)": "Average cycle time in days.",
        },
    },
    "metric_time_in_status": {
        "fields": {
            "Project Key": "Project key.",
            "Status": "Workflow status name.",
            "Status Category": "Status category (To Do / In Progress / Done).",
        },
        "measures": {
            "P50 Duration (hours)": "Median hours spent in the status.",
            "P90 Duration (hours)": "90th percentile hours in the status.",
            "Observations": "Number of transition observations.",
        },
    },
    "metric_flow": {
        "fields": {
            "Flow Date": "Calendar day for created or resolved activity.",
            "Flow Week": "Week of the flow date.",
            "Flow Month": "Month of the flow date.",
            "Project Key": "Project key.",
            "Project Name": "Project display name.",
            "Project Lead": "Project lead display name.",
        },
        "measures": {
            "Created Issues": "Issues created on that date (inflow).",
            "Resolved Issues": "Issues resolved on that date (outflow).",
            "Net Backlog Change": "Created minus resolved. Positive means the backlog grew.",
            "Created Points": "Story points on issues created that day.",
            "Resolved Points": "Story points on issues resolved that day.",
        },
    },
}
